spring.application.name=bookmark-service
server.port=8082
spring.data.mongodb.database=bookmarksdb
#spring.data.mongodb.uri=mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000
spring.data.mongodb.uri=mongodb://localhost:27017/bookmarksdb

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka= true
eureka.client.fetch-registry: true